const XOF = ['XOF', 'XOF(FCFA)']
const XAF = ['XAF', 'XAF(Fcfa centrale)']
const SLE = ['SLE', 'SLE(SLL)']

export { XOF, XAF, SLE }

export default {
    alipay: ['CNY'],
    cinetpay: [...XOF, ...XAF],
    flutterwave: [
        ...XOF,
        ...XAF,
        ...SLE,
        'AED',
        'ARS',
        'AUD',
        'BGN',
        'BHD',
        'BRL',
        'BWP',
        'CAD',
        'CHF',
        'CLP',
        'CNY',
        'COP',
        'CZK',
        'DKK',
        'EGP',
        'ETB',
        'EUR',
        'FCFA',
        'GBP',
        'GHS',
        'GNF',
        'HUF',
        'ILS',
        'INR',
        'JPY',
        'KES',
        'MAD',
        'MUR',
        'MWK',
        'MXN',
        'MYR',
        'NGN',
        'NOK',
        'NZD',
        'PEN',
        'PLN',
        'QAR',
        'RUB',
        'RWF',
        'SAR',
        'SEK',
        'SGD',
        'STD',
        'THB',
        'TRY',
        'TZS',
        'UGX',
        'USD',
        'VEF',
        'ZAR',
        'ZMK',
        'ZMW',
    ],
    orange: ['GNF'],
    pawapay: [...XOF, ...XAF, ...SLE, 'CDF', 'MWK', 'RWF', 'UGX', 'ZMW'],
    paydunya: [...XOF],
    paystack: ['GHS'],
    quikk: ['CDF', 'EGP', 'ETB', 'GHS', 'KES', 'LSL', 'MZN', 'TZS'],
}
