import { computed } from 'vue'

const iconMap = {
    'Apparel & Fabrics': 'icon-shizhuangyufuzhuang-',
    Apparel: 'icon-shizhuangyufuzhuang-1',
    'Apparel Design Services': 'icon-gongyituzhi',
    'Apparel Processing Services': 'icon-fuzhuang-fengrenji',
    'Boy‘s Clothing': 'icon-nantong1',
    'Girl‘s Clothing': 'icon-nvtong1',
    'Women‘s Clothing': 'icon-nvzhuang',
    'Men‘s Clothing': 'icon-nanzhuang',
    'Infant & Toddlers Clothing': 'icon-yinger',
    Uniforms: 'icon-xifu',
    'Garment Accessories& Processing': 'icon-fuzhuang-fengrenji',
    'Maternity Clothing': 'icon-nvzhuang',
    Sportswear: 'icon-yundongfu',
    'Stage & Dance Wear': 'icon-a-43-49_fuzhi-05',
    'Textile & Leather': 'icon-piyi',
    'Down & Feather': 'icon-yurongfu',
    Fabric: 'icon-kehuishouwu-zhiwulei',
    Fiber: 'icon-nanzhuang',
    Fur: 'icon-piyi',
    Leather: 'icon-piyi',
    'Other Textiles & Leather Products': 'icon-jiake',
    'Fashion Accessories': 'icon-erzhuiershizhenzhu',
    'Belt Accessories': 'icon-icon-',
    Belts: 'icon-fuzhuang-yaodai',
    'Fashion Accessories Design Services': 'icon-37gongyegongcheng_mokuaisheji',
    'Fashion Accessories Processing Services': 'icon-yuancailiaojiagong',
    'Gloves & Mittens': 'icon-shenghuoyongpin-',
    'Hats & Caps': 'icon-maozi',
    'Scarves & Shawls': 'icon-weijin',
    'Hair Accessories': 'icon-nvxing',
    'Ties & Accessories': 'icon-lingdai',
    'Jewelry, Eyewear, watch': 'icon-xianglian',
    Eyewear: 'icon-yanjing1',
    Jewelry: 'icon-xianglian',
    Watches: 'icon-shoubiao1',
    'Jewelry accessories': 'icon-erzhuiershizhenzhu',
    'Watch accessories & parts': 'icon-shoubiao',
    'Auto Parts & transportation': 'icon-qiche',
    'Motorcycles & Scooters': 'icon-motuoche',
    Containers: 'icon-baozhuang1',
    'Bus Parts & Accessories': 'icon-bus',
    'Auto Parts & Accessories': 'icon-fangxiangpan',
    'Other Vehicle Parts & Accessories': 'icon-qiche',
    'Marine Parts & Accessories': 'icon-lunchuan',
    'Truck Parts & Accessories': 'icon-kache',
    'Bags, shoes &Accessories': 'icon-xiexiangbao',
    'Bags, luggage, case': 'icon-hanglixiang',
    'Business Bags & Cases': 'icon-wenjianbao',
    'Digital Gear & Camera Bags': 'icon-xiangji',
    'Handbags & Messenger Bags': 'icon-a-ziyuan119',
    'Luggage & Travel Bags': 'icon-hangliewaituoyunhangli',
    'Other Luggage, Bags & Cases': 'icon-shoutibao-',
    'Sports & Leisure Bags': 'icon-xiebaofushi',
    Briefcases: 'icon-wenjianbao',
    'Cosmetic Bags & Cases': 'icon-huazhuangbao',
    'Shopping Bags': 'icon-shangpinshoudai',
    Handbags: 'icon-xiebaofushi',
    Backpacks: 'icon-shubao',
    'Wallets & Holders': 'icon-qianbao_o',
    'shoes &accessories': 'icon-xiezi4',
    'Kid shoes': 'icon-tongxie',
    'outdoor Shoes': 'icon-huwaiyundong',
    'Men‘s Shoes': 'icon-xiezi1',
    'Shoe Materials': 'icon-gouwuche',
    'Shoe Parts & Accessories': 'icon-xiezi01',
    'Shoes care& service': 'icon-caxieji',
    'Women‘s Shoes': 'icon-xiezi101',
    'Other Shoes': 'icon-xiezi2',
    'Agriculture & Food': 'icon-nongchanpin',
    Agriculture: 'icon-wheat__easyic',
    'Agricultural Waste': 'icon-yancaomeiwubing',
    'Animal Products': 'icon-jirou',
    Beans: 'icon-dc-icon-zhongzidujiaoshou',
    'Farm Machinery & Equipment': 'icon-nongji',
    Feed: 'icon-yangji',
    'Fresh Seafood': 'icon-shanbeihaixian',
    Fruit: 'icon-shuiguo',
    Grain: 'icon-wheat__easyic',
    'Herbal Cigars & Cigarettes': 'icon-xiangyan',
    'Mushrooms&Truffiles': 'icon-mogu',
    'Ornamental Plants': 'icon-zhiwuhuapen',
    'Nut&kernel': 'icon-jianguoguopu',
    'Other Agriculture Products': 'icon-mogu',
    'Plant & Animal Oil': 'icon-shiyongyou',
    'Plant Seeds & Bulbs': 'icon-dc-icon-zhongzidujiaoshou',
    'Timber Raw Materials': 'icon-a-ziyuan515',
    Vegetables: 'icon-shucai',
    'Food & Beverage': 'icon-a-50-62_fuzhi-13',
    Beverage: 'icon-yinliao',
    'Baby Food': 'icon-naiping',
    'Baked Goods': 'icon-penghuashipin',
    'Bean Products': 'icon-dc-icon-zhongzidujiaoshou',
    'Canned Food': 'icon-guantou1',
    Confectionery: 'icon-tangguo',
    Dairy: 'icon-lingshiguantou',
    'Egg & Egg Products': 'icon-jidan',
    'Food Ingredients': 'icon-guantou',
    'Fruit Products': 'icon-shuiguo',
    'Grain Products': 'icon-wheat__easyic',
    'Honey Products': 'icon-guantou',
    'Meat & Poultry': 'icon-jirou',
    Seafood: 'icon-shuichanhaixian',
    'Seasonings & Condiments': 'icon-tiaoweipin',
    'Snack Food': 'icon-xianqulingshi',
    'Other Food & Beverage': 'icon-daican',
    'Instant Food': 'icon-fangbianmian_',
    Electronics: 'icon-notebook',
    'Consumer Electronics': 'icon-dianzixue-1',
    'Computer Hardware & Software': 'icon-dianzixue-2',
    'Electronics Cigarettes': 'icon-xiangyan',
    'Accessories & Parts': 'icon-tubiaozhizuomoban-116',
    'Camera, Photo & Accessories': 'icon-zhaoxiangji',
    'Electronics Publications': 'icon-dianziziyuandianzishu',
    'Home Audio, Video & Accessories': 'icon-PMP',
    'Mobile Phone & Accessories': 'icon-shouji',
    'Presentation Equipment': 'icon-dianziyiqi',
    'Blockchain Miner': 'icon-qukuailian',
    'Other Consumer Electronics': 'icon-dianzixue-1',
    'Portable Audio, Video & Accessories': 'icon-MP3',
    'Video Game & Accessories': 'icon-PMP',
    'Mobile Phone Parts': 'icon-shouji',
    'Earphone & Headphone': 'icon-erji',
    'Batteries, Charges & Power Supplies': 'icon-shouji',
    'Radio & TV Accessories': 'icon-dianzixue-',
    Speaker: 'icon-yangshengqi',
    Television: 'icon-dianzixue-',
    'Household appliance': 'icon-leijiayongdianqix',
    'Air Conditioning Appliances': 'icon-kongtiao',
    'Cleaning Appliances': 'icon-qingjie',
    'Hand Dryers': 'icon-winfo-icon-chuanbotuli',
    'Home Appliance Parts': 'icon-dianzixue-',
    'Home Heaters': 'icon-yinshuiji-',
    'Kitchen Appliances': 'icon-chuweidianqi',
    'Laundry Appliances': 'icon-xiyiji',
    'Other Home Appliances': 'icon-dianzixue-',
    'Refrigerators & Freezers': 'icon-jiayongdianqi',
    'Water Heaters': 'icon-yinshuiji-',
    'Water Treatment Appliances': 'icon-winfo-icon-chuanbotuli',
    'Wet Towel Dispensers': 'icon-winfo-icon-chuanbotuli',
    'Vacuum Cleaners& Floor Care': 'icon-xichenqibeifen',
    'Security & Protection': 'icon-anfangguanli',
    'Locks & Keys': 'icon-yuechi',
    'Personal Protective Equipment': 'icon-tubiaozhizuomoban-',
    'Access Control Systems & Products': 'icon-menjin',
    'CCTV Products': 'icon-dianzixue-',
    'Firefighting Supplies': 'icon-miehuoqi',
    'Other Security & Protection Products': 'icon-yongdiananquanfenxi',
    'Roadway Safety': 'icon-zuoyedaolu',
    'Water Safety Products': 'icon-winfo-icon-chuanbotuli',
    'Health & personal care': 'icon-jiankang',
    'health & medical': 'icon-yiliaoweisheng-',
    'Health Care Products': 'icon-baojianpin',
    'Medical Devices': 'icon-yiliaoxiang',
    Medicine: 'icon-daican',
    'Sex Products': 'icon-haixiuhaixiu',
    'Other Health& Medical': 'icon-yiliaoweisheng-',
    'personal care': 'icon-xingzhuang',
    'Baby Care': 'icon-naiping',
    'Bath Supplies': 'icon-yushi',
    'Beauty Equipment': 'icon-meifashalong-2',
    'Breast Care': 'icon-icon-10',
    'Feminine Hygiene': 'icon-nvxing',
    'Fragrance & Deodorant': 'icon-xiangshui',
    'Hair Care': 'icon-meifashalong-2',
    'Hair Extensions & Wigs': 'icon-meifashalong-',
    'Hair Salon Equipment': 'icon-meifashalong-1',
    Makeup: 'icon-xingzhuang',
    'Makeup Tools': 'icon-huazhuanggongju-',
    'Men Care': 'icon-nanshihuli',
    'Nail Supplies': 'icon-meijia',
    'Oral Hygiene': 'icon-kouqianghuli',
    'Other Beauty & Personal Care Products': 'icon-shouye',
    'Sanitary Paper': 'icon-weishengzhi',
    'Shaving & Hair Removal': 'icon-tubiaoCSban-',
    'Skin Care': 'icon-shentihuli',
    'Skin Care Tool': 'icon-xingzhuang',
    'Electronics Equipment & Supply': 'icon-dianzixue-1',
    'Solar Energy Products': 'icon-zu',
    Batteries: 'icon-dianchi',
    'Electrical Instruments': 'icon-dianziyiqi',
    'Connectors & Terminals': 'icon-lianjieqi',
    'Industrial Controls': 'icon-gongyezujian-kaiguan',
    Motors: 'icon-mada',
    'Electrical Supplies': 'icon-dianlijituan',
    Generators: 'icon-fadianji',
    'Professional Audio, Video & Lighting': 'icon-dengguang',
    Switches: 'icon-gongyezujian-kaiguan',
    'Sports, Gifts &Toys': 'icon-yundonghuwaileimu',
    'Sports & Entertainment': 'icon-yundonghuwaileimu',
    'Fitness & Body Building': 'icon-yundong-',
    Gambling: 'icon-majiangtai',
    'Other Sports & Entertainment Products': 'icon-yundonghuwaileimu',
    'Outdoor Sports': 'icon-yundong-1',
    'Indoor Sports': 'icon-yundong-3',
    'Sports Safety': 'icon-yundong-3',
    'Racquet Sport': 'icon-yundong-2',
    'Swimming & Diving': 'icon-yongchi',
    Gifts: 'icon-lihe',
    Crafts: 'icon-gongyi',
    'Arts & Crafts Stocks': 'icon-gupiao',
    'Cross Stitch': 'icon-cixiu',
    'Festive & Party Supplies': 'icon-caideng',
    'Flags, Banners & Accessories': 'icon-tuya_huaban',
    'Gift Sets': 'icon-fuzhuang-waitao',
    toys: 'icon-wanjuxiong',
    Dolls: 'icon-wawa',
    'Educational Toys': 'icon-wanjuxiong',
    'Electronics Toys': 'icon-youxiyouxiji',
    'Glass Marbles': 'icon-yundonghuwaileimu',
    'Inflatable Toys': 'icon-qiqiu',
    'Light-Up Toys': 'icon-toyCar',
    'Outdoor Toys & Structures': 'icon-toyCar',
    'Plastic Toys': 'icon-ertongwanju',
    'other toys': 'icon-ertongwanju',
    'Machinery & Parts': 'icon-tubiaozhizuomoban-116',
    'Apparel & Textile Manufacturing Equipment': 'icon-fuzhuang-fengrenji',
    'Electronics Manufacturing Equipment': 'icon-yiqi',
    'Environmental Equipment': 'icon-zhihuihuanbao_xunjianguanli',
    'Hardware Industry Tooling & Services': 'icon-wujin',
    'Industrial Machinery': 'icon-jixiexingye',
    'Industrial Measuring, Testing & Inspection Equipment': 'icon-dianziyiqi',
    'Industrial Printing & Packaging Supplies': 'icon-yinshuabaozhuang',
    'Industrial Safety & Law Enforcement Equipment': 'icon-etext2dianziwenben',
    'Industrial Supplies': 'icon-yiqi',
    'Manufacturing Equipment': 'icon-tubiaozhizuomoban-116',
    'Material Handling & Construction Machinery': 'icon-jixiexingye',
    'Service Equipment': 'icon-dianzishebei',
    'Home , Lights & Construction': 'icon-jianzhu',
    home: 'icon-jiaju1',
    'Bathroom Products': 'icon-yushiyongpin',
    'Garden Supplies': 'icon-kongzhonghuayuan',
    'Home Decor': 'icon-jiaju-',
    'Home Storage & Organization': 'icon-jiaju-3',
    'Household Sundries': 'icon-jiaju-1',
    'Kitchen & Tableware': 'icon-jiaju-4',
    'Pet Products': 'icon-chongwugoupen',
    'Baby Supplies & Products': 'icon-naiping',
    'Rain Gear': 'icon-yuju',
    'Children Furniture': 'icon-jiaju',
    'Commercial Furniture': 'icon-jiaju-2',
    'Folding Furniture': 'icon-jiaju-4',
    'Other Furniture': 'icon-jiaju',
    'Light & Lighting': 'icon-zhaoming',
    'Indoor Lighting': 'icon-zhaoming1',
    'Lighting Accessories': 'icon-zhaoming',
    'Lighting Bulbs & Tubes': 'icon-xingzhuang1',
    'Other Lights & Lighting Products': 'icon-dengguang',
    'Outdoor Lighting': 'icon-zhaoming-kai',
    'Professional Lighting': 'icon-taideng',
    Construction: 'icon-shigong',
    'Aluminum Composite Panels': 'icon-zhongban4',
    'Balustrades & Handrails': 'icon-loutistairs7',
    Bathroom: 'icon-yushi',
    'Building Glass': 'icon-boli',
    Ceilings: 'icon-diban',
    'Corner Guards': 'icon-duliweishengjian',
    'Countertops, Vanity Tops & Table Tops': 'icon-shuzhuangtai',
    'Curtain Walls & Accessories': 'icon-24gl-bricks',
    'Decorative Films': 'icon-tiezhi',
    'Door & Window Accessories': 'icon-menchuang',
    'Other constructions': 'icon-jianzhu',
    'Packaging & Office& Business ': 'icon-bangongzhuo',
    Packaging: 'icon-baozhuang1',
    'Chemical Packaging': 'icon-V3',
    'Composite Packaging Materials': 'icon-V1',
    'Cosmetics Packaging': 'icon-xiaoxinqingfangwaibaozhuangxiangtubiao',
    'Electronics Packaging': 'icon-xiaoxinqingfangwaibaozhuangxiangtubiao',
    'Food Packaging': 'icon-V3',
    'Gift Packaging': 'icon-lihe',
    'Other Packaging Applications': 'icon-wuliaobaozhuangdan',
    'office& school Supplies': 'icon-tushu',
    'Art Supplies': 'icon-meishu1',
    'Badge Holder & Accessories': 'icon-Name-Tag',
    'Board Eraser': 'icon-baiban',
    'Book Cover': 'icon-wenanfengmian',
    Books: 'icon-tushu',
    Calculator: 'icon-jisuanqi_o',
    Calendar: 'icon-rili',
    Clipboard: 'icon-clipboard',
    'Correction Supplies': 'icon-winfo-icon-chuanbotuli',
    'Desk Organizer': 'icon-bangongzhuo',
    'Drafting Supplies': 'icon-meishu1',
    Easels: 'icon-meishu',
    'Educational Supplies': 'icon-wenjubangongyongpin',
    'Filing Products': 'icon-jishiben',
    'Letter Pad / Paper': 'icon-zhizhang4',
    Magazines: 'icon-zazhiqikan',
    Map: 'icon-dituleiditu',
    'Notebooks & Writing Pads': 'icon-wenjubangongyongpin',
    'Office Adhesives & Tapes': 'icon-jiaodai',
    'Advertising Equipment': 'icon-ad',
    'Cargo & Storage Equipment': 'icon-cangku_kucun_o',
    'Commercial Laundry Equipment': 'icon-xiyiji',
    'Financial Equipment': 'icon-gupiao',
    'Funeral Supplies': 'icon-huadian-huaquan',
    'Other Service Equipment': 'icon-shebeiguanli',
    'Restaurant & Hotel Supplies': 'icon-jiudiancanting-',
    'Store & Supermarket Supplies': 'icon-chaoshi',
    'Recycled Prodcuts& Environment Friendly': 'icon-huanbao',
    'Recycled Products': 'icon-kehuishouwu',
    'Recycled Projects': 'icon-kehuishouwu-suliaolei',
    'Recycled Plastic': 'icon-kehuishouwu-suliaolei',
    'Recycled Rubber': 'icon-kehuishouwu-suliaolei',
    'Environment Friendly': 'icon-huanbao',
    'Environment-Friendly Products': 'icon-huanbaopingtai-huanbaohesuan',
    'Environment-Friendly Projects': 'icon-kehuhuishouzhan',
    'Home,Lights & Construction': 'icon-zhaoming1',
    'Packaging & Office& Business': 'icon-bangongzhuo',
    'Recycled Prodcuts& Environment- Friendly': 'icon-huanbao1',
}

function getRouter() {
    try {
        const vm = window.vm || (window.__VUE_DEVTOOLS_GLOBAL_HOOK__ && window.__VUE_DEVTOOLS_GLOBAL_HOOK__.apps && window.__VUE_DEVTOOLS_GLOBAL_HOOK__.apps[0])
        return (vm && vm.$router) || null
    } catch (e) {
        return null
    }
}

export default function useNav(props) {
    const filterList = computed(() => {
        if (Array.isArray(props.list)) {
            return props.list.slice(0, 10)
        }
        return []
    })

    function navtoProductlist(id = '') {
        const router = getRouter()
        if (!router) {
            console.warn('useNav: no router available')
            return
        }
        router.push({
            path: '/v2/product/list',
            query: id.length
                ? {
                      cid: id,
                  }
                : {},
        })
    }

    return {
        iconMap,
        filterList,
        navtoProductlist,
    }
}
